### PR TITLE
Update marked.js

### PR DESCRIPTION
**Pull request by tjfoerster**
#176 finished

### CODE REVIEW

**Review by dboehmer — CHANGES_REQUESTED** [review]
Looks good :+1: Git says there are conflicts. Can you rebase on master **after** #175 was merged?

**Comment by dboehmer** [comment]
> Looks good +1 Git says there are conflicts. Can you rebase on master **after** #175 was merged?

Ready for rebase :rocket:

**Comment by dboehmer** [comment]
Doesn’t look quite like I expected :smile: You see how your branch duplicates commits from `master` but diverges earlier on?

image

Don’t know how you created this but you’ll need to `git fetch && git rebase -i origin/master` and keep only the two commits that I marked with green. You probably meant to squash them together to 1 commit because you used the exact same commit message.

**Comment by tjfoerster** [comment]
`git rebase -i origin/master` was exactly what I did. Mhh. 🤔 Maybe it was too late... ⌚ 😄

**Pull request merged**
