### PR TITLE
Offset handling

### PR DESCRIPTION
**Pull request by moseschmiedel**

### CODE REVIEW

**Comment by moseschmiedel** [comment]
Yeah, I think we can merge this into master.

**Comment by dboehmer** [comment]
We discovered new TODOs together:

- [ ] display offset in list of dishes on purchase list **print view**
- [ ] remove `ca.` in print view
- [ ] display `+` or `-` icon after article name in print view if offset (`+` for positive offsets)
- [ ] #109 (this PR can be completed without this)

Do **not** display the offset as virtual dish in _print_ view.

**Comment by moseschmiedel** [comment]
> We discovered new TODOs together:
> 
>     * [ ]  display offset in list of dishes on purchase list **print view**
> 
>     * [x]  remove `ca.` in print view
> 
>     * [x]  display `+` or `-` icon after article name in print view if offset (`+` for positive offsets)
> 
>     * [ ]  #109 (this PR can be completed without this)
> 
> 
> Do **not** display the offset as virtual dish in _print_ view.

How should the offset be displayed in the print view? Should we introduce a new column for it?

**Comment by dboehmer** [comment]
Did you realize that these subtasks were solely for the print view? I think they should describe exhaustively what needs to be changed. If anything particular is unclear please ask more pricesely :stuck_out_tongue:

**Comment by moseschmiedel** [comment]
Yes I realized, that these tasks were for the print view. What made me think was, that in the checklist it is written, that the offset should be displayed in the list of dishes, but underneath the checklist it is written that the offset should not be displayed as a virtual dish, so I wondered how I should display the offset in the list of dishes, when it should not look like a virtual dish?

**Comment by dboehmer** [comment]
> Yes I realized, that these tasks were for the print view. What made me think was, that in the checklist it is written, that the offset should be displayed in the list of dishes, but underneath the checklist it is written that the offset should not be displayed as a virtual dish, so I wondered how I should display the offset in the list of dishes, when it should not look like a virtual dish?

Resolution: we display the offset in the print view as well and wait for user feedback on how to change that.

Advantages:
* having a decision allows progress
* edit view looks equally to print view and both can be merged

**Pull request merged**
